name: CI/CD Deployment to Azure App Service

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout the code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Étape 3 : Installer Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      # Étape 4 : Installer les dépendances avec Poetry
      - name: Install dependencies
        run: poetry install --no-root

      # Étape 5 : Lancer les tests avec pytest
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: poetry run pytest

      # Étape 6 : Se connecter à Azure avec le profil de publication
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 7 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ env.AZURE_APP_NAME }} .

      # Étape 8 : Déployer l'application sur Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          images: ${{ env.AZURE_APP_NAME }}
